##
## This Docker Compose file may be modified and distributed under the terms
## of the MIT license.  See the LICENSE file for details.
## https://github.com/fogfish/makefile
##
## @doc
##   An example docker compose file to spawn Erlang releases  
##
## @version 1.0.0
version: '3'

services:
  local:
    build:
      context: .
      dockerfile: _build/spawner

    ports:
     - "8888:8888"

